name: Send HTTP Request and Print Response

on:
  push:
    branches:
      - main
  workflow_dispatch: # manuel tetikleme için

jobs:
  http-request-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install curl
      run: sudo apt-get install curl

    - name: Send HTTP request with headers and referer
      run: |
        curl -X GET "https://sportsobama.com/domain.php" \
        -H "User-Agent: Mozilla/5.0" \
        -H "Referer: https://sportsobama.com" \
        -H "Authorization: Bearer token" # İstediğiniz header'ları buraya ekleyebilirsiniz

    - name: Print response
      run: echo "HTTP request sent successfully!"
