name: GitHub Repo Yedekleme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *"

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Ana repo checkout
        uses: actions/checkout@v4

      - name: Python kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Python baÄŸÄ±mlÄ±lÄ±klarÄ±
        run: |
          pip install --upgrade pip
          pip install requests

      - name: Python backup script Ã§alÄ±ÅŸtÄ±r
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          YEDEKLEME_TOKENI: ${{ secrets.YEDEKLEME_TOKENI }}
        run: |
          python kanallogolari/backup.py
          ls -lah || true

      - name: Yedek repo clone
        run: |
          git clone https://MDuymaz:${{ secrets.YEDEKLEME_TOKENI }}@github.com/MDuymaz/yedeklemesistemi.git backup-repo


      - name: Zip dosyalarÄ±nÄ± yedek repo'ya kopyala
        run: |
          shopt -s nullglob
          cp *.zip backup-repo/ || echo "Kopyalanacak zip yok"

      - name: Commit ve push (yedek repo)
        run: |
          cd backup-repo
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add .
          git commit -m "ðŸ”„ Otomatik yedekleme - $(date '+%Y-%m-%d %H:%M')" || echo "DeÄŸiÅŸiklik yok"
          git push

      - name: Telegram Success Notification
        if: success()
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          MESSAGE="âœ… GitHub Repo Yedekleme baÅŸarÄ±yla tamamlandÄ±!"
          curl -s -o /dev/null -X POST "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage" \
            -d chat_id="$TELEGRAM_CHAT_ID" \
            -d text="$MESSAGE"
