name: GitHub Repo Yedekleme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Repo A checkout
        uses: actions/checkout@v4

      - name: Python kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Python baÄŸÄ±mlÄ±lÄ±klarÄ±
        run: |
          pip install requests

      - name: Python backup script Ã§alÄ±ÅŸtÄ±r
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          python kanallogolari/backup.py
          ls -lah *.zip

      - name: Yedek repo clone
        run: |
          git clone https://${{ secrets.YEDEKLEME_TOKENI }}@github.com/MDuymaz/yedeklemesistemi.git backup-repo

      - name: Zip dosyalarÄ±nÄ± yedek repo'ya kopyala
        run: |
          cp *.zip backup-repo/

      - name: Commit ve push (yedek repo)
        run: |
          cd backup-repo
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add .
          git commit -m "ðŸ”„ Otomatik yedekleme - $(date '+%Y-%m-%d %H:%M')" || echo "DeÄŸiÅŸiklik yok"
          git push

      - name: Telegram Success Notification
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        if: success()
        run: |
          MESSAGE="âœ… Yedekleme Sistemi baÅŸarÄ±yla gÃ¼ncellendi!"
          curl -s -o /dev/null -X POST "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage" \
            -d chat_id="$TELEGRAM_CHAT_ID" \
            -d text="$MESSAGE"
